### ISSUE TITLE
Image wrongly listed as unused

### ISSUE THREAD

**Issue by BenDDD** [wilhelmer/mkdocs-unused-files#5]
Hi,

I'm trying to use this plugin to sort through documents that are no longer used but the plugin shows an image as unused when it is on a page.

**mkdocs.yml**

    site_name: xxx
    repo_url: https://xxx/xxx/wiki/
    edit_uri: edit/master/docs/
    theme:
        name: 'material'
    plugins:
        - search
        - awesome-pages
        - unused_files:
            dir: media
            file_types:
              - png
              - jpg
              - pdf
              - xlsx
              - docx
              - gv
    markdown_extensions:
        - codehilite

**Plugin output**

    INFO     -  The following files exist in the docs directory, but may be unused:
                  - media/index.png

**HTML code of the page using the image**

    <p><img alt="devops" src="[/media/index.png](view-source:https://xxx/media/index.png)" /></p>

Did I configure the plugin incorrectly?

Thank you in advance for your help.

**Comment by wilhelmer** [comment]
Thanks for your feedback! That's some weird HTML code. Why is there Markdown code in the `src` part? It should be 

```html
<p><img alt="devops" src="https://xxx/media/index.png" /></p>
```

With correctly formatted HTML code, the plugin should work.

**Comment by BenDDD** [comment]
Hi @wilhelmer 

It's mkdocs that generates the HTML for the pages, so I don't know why it's worded that way.

Here is the original markdown code:

``` bash
![devops](/media/index.png)
```

**Comment by wilhelmer** [comment]
I think it should be `![devops](media/index.png)` (without the leading slash, i.e., `media` instead of `/media`).

Does that solve the issue?

**Comment by BenDDD** [comment]
This syntax does not display the image in the HTML page anymore. It just print "devops".

The plugin output this

    WARNING  -  Documentation file 'Developpement/Test-devops/test.md' contains a link to
            'Developpement/Test-devops/media/index.png' which is not found in the
            documentation files.

**Comment by wilhelmer** [comment]
So your image file isn't in `Developpement/Test-devops/media/`? Where is it then? 

I think it would be helpful if you could provide your test project as a ZIP file.

**Comment by BenDDD** [comment]
I cannot share the project because it contains confidential information.

The image files are at the root of the project in /media/

**Comment by wilhelmer** [comment]
All image files must be in the `docs_dir` folder, which is `docs` by default. So they should be in `docs/media`.

**Comment by BenDDD** [comment]
Sorry, I expressed myself badly. The images are actually in /var/www/html/docs.git/docs/media

**Comment by wilhelmer** [comment]
Please provide a minimal reproduction as described [here](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by BenDDD** [comment]
Hello,

Sorry for not replying sooner, I'm overwhelmed with work right now. I have to take the time to read the procedure to provide a minimal reproduction.
