### ISSUE TITLE
list is not getting refreshed

### ISSUE THREAD

**Issue by onixpro** [wilhelmer/mkdocs-unused-files#6]
Hi,

In mkdocs serve mode very time files changed and medocs rebuilds pages the list of unused files getting bigger and bigger.
looks like the list of unused files is not getting refreshed between builds.

**Comment by wilhelmer** [comment]
Thanks for reporting! I never use `mkdocs serve` and haven't tested it against that. I guess I'll simply disable the plugin in serve mode.

**Comment by wilhelmer** [comment]
Fixed in d4d10af0a10a70f16c577907cb927f49153668e5.
